### ISSUE TITLE
git remote detection failing w/o HEAD ref

### ISSUE THREAD

**Issue by rednexela1941** [princjef/gomarkdoc#34]
If the repository does not have a ref to HEAD (ie. it was created locally, not cloned) the remote will go undetected and urls will be missing from the docs.

Temporary fix is to manually add `git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/$(default_branch)`. 

Any ideas on a nice way to handle this case inside the gomarkdoc without making any surprising assumptions?

**Comment by princjef** [comment]
Hi @rednexela1941, sorry for the delayed response!

You're right that the remote detection is a bit fragile because it depends on trying to sniff information from your local repository. the `HEAD` ref is the only way I know of to detect the default branch locally.

If you can't trust the `HEAD` ref to be present, you can simply include the `--repository.default-branch` option and set it equal to your default branch. This will fill in the missing gap and allow the branch to be filled in. You can also set the option via the file configuration (there's an example here - https://github.com/princjef/gomarkdoc/blob/master/.gomarkdoc.yml)

**Comment by princjef** [comment]
Going to close this but just let me know if you still have issues/questions
