### ISSUE TITLE
Generate wrong index for go 1.18 generic code

### ISSUE THREAD

**Issue by chen3feng** [princjef/gomarkdoc#80]
eg:

> [type DList](https://github.com/chen3feng/contalgo/blob/master/README.md#type-dlist)
> [func NewDList[T any](https://github.com/chen3feng/contalgo/blob/master) *DList[T]](<#func-newdlist>)

See the following link for more examples:

https://github.com/chen3feng/contalgo/blob/decca4ca119775b6bed62a1ef5b35e76696f17f3/README.md#index

Thanks.

**Comment by MarvinJWendt** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/31022056/194727691-6e453afd-49d6-4acb-a45f-678b03965096.png)

**Comment by thediveo** [comment]
There is probably more wrong markdown generated here than just the line you point out. Looking at the other links generated, they rather tend to work by accident, because `[...]` is not immediately followed by `(...)`. I'm afraid the whole markdown thing is falling apart in light of Go generics, as there is no common markdown way to escape square/rounded brackets in order to not totally confuse markdown interpreters in case of Go generics signatures.

**Comment by MarvinJWendt** [comment]
@princjef any update on this?

**Comment by egonelbre** [comment]
One fix would be to replace `[]()` with their html code counterpart:

```
r := strings.NewReplacer(
	"[", "&#91;",
	"]", "&#93;",
	"(", "&#40;",
	")", "&#41;",
)
```

https://go.dev/play/p/MMr04QkvnTW -- although, that would be really annoying when reading in an editor.

But, yeah, the `strings.ReplaceAll(s, "](", "]\(")` seems like a nicer output.

Also, there's an option to replace them with some similar unicode-symbol, e.g. https://symbl.cc/en/27E6/.

**Comment by princjef** [comment]
Gomarkdoc does some general escaping with `\` which generally solves this problem, I think it's just being skipped here (accidental omission). Let me see if applying that escaping is enough without messing up the rendering. Raw readability of the code will suffer, but up until now I've favored proper rendering over maximum readability of the raw code
