### ISSUE TITLE
git branch issue when running in ci environment

### ISSUE THREAD

**Issue by jabalsad** [princjef/gomarkdoc#84]
Hello,

I seem to have an oddity between my local environment and a github actions environment. Some context:

- gomarkdoc v0.4.1
- go v1.19.5
- the repository is a private github repository

I'm using github actions to run `gomarkdoc`, but with debug logging i see the following error:

```
skipping remote https://github.com/private/go-lib-env because no default branch was found
```

Strangely enough, on my local machine this does not happen:

```
DEBUG found default branch main for remote git@github.private/go-lib-env.git dir=./pkg/env
```

All my other go tools work just fine:
- i use `git config --global url."https://username:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"` to configure https access to the git repos
- i also set `export GOPRIVATE=github.com/private` for access to private repos.

I still can't quite figure out why this doesn't work on the github actions build server.

**Comment by princjef** [comment]
Hi @jabalsad, this is actually a common scenario in CI environments due to how they perform checkout of the repository. The various `repository` options are available to ensure reliable builds/linking across environments: https://github.com/princjef/gomarkdoc#additional-options

For CI of gomarkdoc itself, these options are specified in the [.gomarkdoc.yml](https://github.com/princjef/gomarkdoc/blob/master/.gomarkdoc.yml#LL7C1-L10C10) file

Give it a shot and see if that solves your problem

**Comment by princjef** [comment]
Marking this closed as the solution above should resolve the issue. Feel free to reopen if it doesn't work for you
