### ISSUE TITLE
Ignore vendor folder

### ISSUE THREAD

**Issue by amayausky** [princjef/gomarkdoc#94]
I did not see this issue covered, or a supported way to do this. Please let me know if I missed something.

When running `gomarkdoc -o '{{.Dir}}/README.md' ./...` from a project's root where `go mod vendor` has been used, `gomarkdoc` parses and creates `README.md` files in all vendored paths as well as expected paths. Since `vendor` is a standard path for vendored code `gomarkdoc` should ignore that folder by default.

Alternatively, there should be a way to ignore specific paths when invoking the command.

**Comment by princjef** [comment]
Hi @amayausky, I've received other requests in the past for excluding folders from documentation generation and I think it's a reasonable thing to add. I'd rather add it as a general set of "excludes" so that people can tailor it to their needs. Would that work for you? (something like `--exclude ./vendor` on CLI invocation)

**Comment by amayausky** [comment]
That seems like a reasonable approach. It might also be useful to allow excluding both directories and packages separately. That way if you're adding code to a legacy project that already has non-generated documentation you don't risk stomping that.

**Comment by princjef** [comment]
Excluding resolved package names is a bit more complicated since it happens later in the process. I've started with a directory exclude for now. Package-based exclusion can be added later if a specific need arises.

**Comment by princjef** [comment]
This is now available in v1.1.0
